const course=JSON.parse(document.getElementById('course-data').textContent);
const KEY='ai-campus-foundation-preview-v1';
const fresh=()=>({courseVersion:course.version,lessonIndex:0,view:'read',reviewMode:false,confirmed:{},presented:[],attempts:[],notes:{},quiz:null,remediated:{}});
let state=fresh(),storageAvailable=true;
try{const raw=JSON.parse(localStorage.getItem(KEY)||'null');if(raw&&raw.courseVersion===course.version&&Array.isArray(raw.attempts)&&raw.confirmed&&raw.notes&&Array.isArray(raw.presented)&&raw.remediated)state={...fresh(),...raw};}catch{}
if(!Number.isInteger(state.lessonIndex)||!course.lessons[state.lessonIndex])state.lessonIndex=0;
if(!['read','quiz','result','records'].includes(state.view))state.view='read';
if((state.view==='quiz'||state.view==='result')&&(!state.quiz||state.quiz.lessonId!==course.lessons[state.lessonIndex].id))state.view='read';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const current=()=>course.lessons[state.lessonIndex];
const done=l=>l.objectives.every(o=>state.confirmed[o.id]);
const unlocked=i=>state.reviewMode||course.lessons.slice(0,i).every(done);
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageAvailable=false;document.getElementById('announce').textContent='このブラウザには保存できません。画面を閉じると進捗が失われます。';}}
function announce(text){document.getElementById('announce').textContent=text;}
function moveTop(){document.getElementById('main').focus();window.scrollTo({top:0,behavior:'auto'});}
function render(){
 const l=current(),completed=course.lessons.filter(done).length;
 document.getElementById('review-switch').checked=state.reviewMode;
 document.getElementById('sidebar').innerHTML=`<span class="eyebrow aside-eyebrow">基礎コース 1</span><h2>${esc(course.title)}</h2><p class="aside-note">全12レッスン · 自分のペースで</p><nav class="lesson-nav">${course.lessons.map((x,i)=>`<button class="nav-item ${i===state.lessonIndex?'active':''}" data-lesson="${i}" ${unlocked(i)?'':'disabled'} ${i===state.lessonIndex?'aria-current="step"':''}><span class="nav-num">${String(i+1).padStart(2,'0')}</span><span>${esc(x.title)}</span><small>${done(x)?'✓':unlocked(i)?'':'未解放'}</small></button>`).join('')}</nav><div class="aside-progress"><div class="track"><span style="width:${completed/course.lessons.length*100}%"></span></div><p>理解を確認したレッスン ${completed} / ${course.lessons.length}</p></div><button class="aside-link" data-action="records">学習の記録</button><button class="aside-link" data-action="export">記録を書き出す</button><button class="aside-link" data-action="reset">この体験の進捗をリセット</button>`;
 let html=state.reviewMode?'<div class="review-warning">講師確認モード：教材を見比べるため、未修了のレッスンも開けます。この切り替え自体では合格記録は付きません。</div>':'';
 if(!storageAvailable)html+='<div class="review-warning">この環境では進捗を保存できません。必要に応じて記録を書き出してください。</div>';
 if(state.view==='records')html+=records();
 else{
  html+=`<span class="eyebrow">第${state.lessonIndex+1}レッスン / 全12レッスン</span><h1>${esc(l.title)}</h1><p class="lead">${esc(l.goal)}</p>`;
  if(state.view==='read')html+=reading(l);
  else if(state.view==='quiz')html+=quiz(l);
  else html+=results(l);
 }
 document.getElementById('main').innerHTML=html;
}
function reading(l){const session=state.quiz?.lessonId===l.id?state.quiz:null;const resume=session&&!session.graded;const retry=session?.graded&&session.rows.some(r=>!r.result.correct);return `<section class="lesson-map" aria-label="今回学ぶこと"><h2>今回覚えること</h2><ol>${l.objectives.map(o=>`<li><a href="#${o.id}">${esc(o.title)}</a></li>`).join('')}</ol><p>下の解説で確かめてから、最後に3問の確認問題へ進みます。</p></section><p class="terms-label">今回使う言葉</p><div class="tags">${l.terms.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>${done(l)?'<p class="muted">✓ このレッスンは確認済みです。解説と問題は復習できます。</p>':''}${l.objectives.map((o,i)=>`<section class="reading" id="${o.id}"><div class="reading-heading"><span class="section-no">${i+1}</span><h2>${esc(o.title)}</h2></div><div class="key-point"><strong>ここを押さえる</strong><p>${esc(o.keyPoint)}</p></div>${o.body.map(p=>`<p>${esc(p)}</p>`).join('')}${o.diagram.length?`<div class="flow" aria-label="${esc(o.title)}の関係図">${o.diagram.map((d,j)=>`${j?'<span class="flow-arrow" aria-hidden="true">→</span>':''}<div class="flow-box">${esc(d)}</div>`).join('')}</div>`:''}<div class="example"><strong>具体例</strong>${esc(o.example)}</div></section>`).join('')}<section class="lesson-summary"><h2>確認問題の前に、おさらい</h2><ul>${l.objectives.map(o=>`<li>${esc(o.keyPoint)}</li>`).join('')}</ul><p>説明できないところがあれば、上の解説に戻って確かめてください。</p></section><section class="practice"><h2>自分の言葉で確かめる</h2><p>${esc(l.practice)}</p><label for="practice-note" class="muted">学習メモ（自動採点はしません。分からないことは「未確認」と残せます）</label><textarea id="practice-note" placeholder="分かったこと、確認したこと、まだ分からないこと…">${esc(state.notes[l.id]||'')}</textarea><span class="muted" id="note-status">${state.notes[l.id]?'保存したメモを表示しています。':'記入した内容は、このブラウザに保存します。'}</span></section><p class="muted">確認問題は3問。時間制限はありません。ヒントを使いながら進められます。</p><div class="actions"><button class="secondary" data-action="pause">ここで休む・保存する</button><button class="primary" data-action="${resume?'resume':retry?'retry':'start'}">${resume?'回答途中の問題に戻る':retry?'補足を確認した・別の問題で試す':done(l)?'別の問題で復習する':'理解した・確認へ進む'} →</button></div>`;}
function lookup(l,row){const o=l.objectives.find(o=>o.id===row.objectiveId);return {o,q:o.questions.find(q=>q.id===row.questionId)};}
function quiz(l){const s=state.quiz;return `<p class="muted">${s.rows.length}問を確認します。回答をまとめて選んでから「回答を確認する」を押してください。</p><form id="quiz-form">${s.rows.map((r,i)=>{const {o,q}=lookup(l,r);return `<section class="question"><span class="question-header">問題 ${i+1} / ${s.rows.length} · ${q.type==='multiple_choice'?'当てはまるものをすべて選択':'一つ選択'}</span><fieldset><legend>${esc(q.prompt)}</legend>${r.choiceOrder.map(id=>{const c=q.choices.find(c=>c.id===id);return `<label class="choice"><input type="${q.type==='multiple_choice'?'checkbox':'radio'}" name="${q.id}" value="${c.id}" data-question="${q.id}" ${r.selected.includes(c.id)?'checked':''}><span>${esc(c.text)}</span></label>`;}).join('')}</fieldset><details class="hint" data-hint="${q.id}" ${r.hintUsed?'open':''}><summary>ヒントを見る</summary><p>${esc(o.hint)}</p></details></section>`;}).join('')}<div id="quiz-error" class="error" role="alert"></div><div class="actions"><button type="button" class="secondary" data-action="read">解説に戻る</button><button class="primary" type="submit">回答を確認する →</button></div></form>`;}
function results(l){const s=state.quiz,all=s.rows.every(r=>r.result.correct);return `<section class="success"><span class="eyebrow">${all?'理解の確認':'復習と再確認'}</span><h2>${all?'確認できました。次の一歩へ。':'ここをもう一度、確認しましょう。'}</h2><p>${all?'確認した内容を、別の場面でも使えるか少しずつ確かめていきましょう。':'正解した項目はそのままに、つまずいた項目を別の例で見直します。'}</p></section>${s.rows.map(r=>{const {o,q}=lookup(l,r);return `<section class="question"><h3>${esc(o.title)}<span class="badge">${r.result.correct?(r.hintUsed||r.supported?'補助ありで確認':'今回ヒントなしで正解'):'復習する'}</span></h3><p>${esc(q.prompt)}</p><p class="muted">あなたの回答：${r.selected.map(id=>esc(q.choices.find(c=>c.id===id).text)).join(' ／ ')}</p><div class="feedback ${r.result.correct?'':'review'}"><strong>${r.result.correct?'✓ 正解です':'考え方を確認しましょう'}</strong><p>${esc(q.explanation)}</p>${!r.result.correct?`<p>${esc(o.remediation)}</p><p><b>別の例：</b>${esc(o.example)}</p><button class="secondary" data-review="${o.id}">この解説を読み直す</button>`:''}</div></section>`;}).join('')}<div class="actions"><button class="secondary" data-action="pause">ここで休む・保存する</button>${all?`<button class="primary" data-action="next">${state.lessonIndex<course.lessons.length-1?'次のレッスンへ →':'学習記録と修了課題を見る →'}</button>`:'<button class="primary" data-action="retry">補足を確認した・別の問題で試す →</button>'}</div>`;}
function records(){return `<span class="eyebrow">学習の記録</span><h1>学んだ過程を振り返る</h1><p class="lead">正答だけでなく、ヒントや補足を使った履歴も残します。少ない回答から、定着や意欲、不正の有無は断定しません。</p>${course.lessons.map(l=>{const a=state.attempts.filter(a=>a.lessonId===l.id);return `<section class="record"><h3>${esc(l.title)}<span class="badge">${done(l)?'確認済み':'学習途中・未着手'}</span></h3><p>回答 ${a.length}件 · ヒントなし正解 ${a.filter(a=>a.correct&&!a.hintUsed&&!a.supported).length}件 · 補助あり正解 ${a.filter(a=>a.correct&&(a.hintUsed||a.supported)).length}件</p>${l.objectives.map(o=>`<p>${esc(o.title)}：${state.confirmed[o.id]?(state.confirmed[o.id].assisted?'補助ありで確認済み':'確認済み'):'未確認'}</p>`).join('')}</section>`;}).join('')}<section class="practice"><h2>コース修了課題：自分のPC説明書</h2><p>機器の構成、OS、使用アプリ、保存場所、文書を編集・保存する流れを、自分の環境に沿って説明します。確認元と未確認事項を分けて記録してください。</p><p>このプレビューでは、課題の提出・講師の確認はまだ行えません。ミニテストの完了だけで、コース修了認定や実務能力の保証は行いません。</p></section><button class="secondary" data-action="read">レッスンに戻る</button>`;}
function startQuiz(retry=false){const l=current();const confirmed=retry?Object.fromEntries(state.quiz.rows.filter(r=>r.result.correct).map(r=>[r.objectiveId,true])):{};
 if(retry){for(const o of l.objectives)if(!state.quiz.rows.some(r=>r.objectiveId===o.id))confirmed[o.id]=true;}
 const rows=LearningEngine.pick(l,confirmed,state.presented).map(r=>({...r,supported:!!state.remediated[r.objectiveId]}));
 state.presented.push(...rows.map(r=>r.questionId));
 state.quiz={id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),lessonId:l.id,lessonVersion:l.version,rows,startedAt:new Date().toISOString(),graded:false};state.view='quiz';save();render();moveTop();}
document.addEventListener('input',e=>{if(e.target.id==='practice-note'){state.notes[current().id]=e.target.value;save();document.getElementById('note-status').textContent=storageAvailable?'保存しました。':'保存できません。記録を書き出してください。';}});
document.addEventListener('change',e=>{if(e.target.id==='review-switch'){state.reviewMode=e.target.checked;if(!unlocked(state.lessonIndex)){state.lessonIndex=course.lessons.findIndex(l=>!done(l));state.view='read';state.quiz=null;}save();render();return;}if(e.target.dataset.question&&state.quiz&&!state.quiz.graded){const r=state.quiz.rows.find(r=>r.questionId===e.target.dataset.question);r.selected=[...document.querySelectorAll(`input[data-question="${r.questionId}"]:checked`)].map(x=>x.value);save();}});
document.addEventListener('toggle',e=>{if(e.target.matches('details[data-hint]')&&e.target.open&&state.quiz&&!state.quiz.graded){const r=state.quiz.rows.find(r=>r.questionId===e.target.dataset.hint);if(r){r.hintUsed=true;save();}}},true);
document.addEventListener('submit',e=>{if(e.target.id!=='quiz-form')return;e.preventDefault();if(state.quiz.graded)return;const l=current();try{const graded=state.quiz.rows.map(r=>({...r,result:LearningEngine.grade(lookup(l,r).q,r.selected)}));state.quiz.rows=graded;for(const r of graded){const {q}=lookup(l,r);if(r.result.correct){state.confirmed[r.objectiveId]={assisted:r.hintUsed||r.supported,at:new Date().toISOString()};}else{state.remediated[r.objectiveId]=true;}state.attempts.push({attemptId:state.quiz.id,lessonId:l.id,lessonVersion:l.version,questionId:q.id,questionVersion:q.version,objectiveId:r.objectiveId,presentedChoiceOrder:r.choiceOrder,selectedChoiceIds:r.selected,correct:r.result.correct,itemResults:r.result.itemResults,hintUsed:r.hintUsed,supported:r.supported,presentedAt:state.quiz.startedAt,answeredAt:new Date().toISOString()});}state.quiz.graded=true;state.view='result';save();render();moveTop();}catch(error){document.getElementById('quiz-error').textContent=error.message+' 未回答の問題がないか確認してください。';}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.lesson!==undefined){const i=Number(b.dataset.lesson);if(!unlocked(i))return;state.lessonIndex=i;state.view='read';state.quiz=null;save();render();moveTop();return;}
 if(b.dataset.review){state.view='read';save();render();const section=document.getElementById(b.dataset.review);section.scrollIntoView({behavior:'auto'});section.setAttribute('tabindex','-1');section.focus();return;}
 const a=b.dataset.action;
 if(a==='resume'){state.view='quiz';save();render();moveTop();return;}if(a==='start'){startQuiz();return;}if(a==='retry'){startQuiz(true);return;}
 if(a==='read'){state.view='read';save();render();moveTop();}
 if(a==='records'){state.view='records';save();render();moveTop();}
 if(a==='next'){if(state.lessonIndex===course.lessons.length-1){state.view='records';}else if(unlocked(state.lessonIndex+1)){state.lessonIndex++;state.view='read';state.quiz=null;}save();render();moveTop();}
 if(a==='pause'){save();announce(storageAvailable?'現在の進捗を保存しました。閉じて、後で続きから再開できます。':'保存できません。記録を書き出してください。');b.textContent=storageAvailable?'保存しました。いつでも再開できます':'保存できません';}
 if(a==='export'){const blob=new Blob([JSON.stringify({schemaVersion:1,exportedAt:new Date().toISOString(),courseId:course.id,...state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='ai-campus-learning-record.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 if(a==='reset'&&window.confirm('このプレビューの学習記録とメモをリセットします。よろしいですか？')){state=fresh();save();render();moveTop();}
});
render();
